# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thoughts',
            options={'ordering': ['-recorded_at']},
        ),
    ]
